[versions]
detekt = "2.0.0-alpha.3"
dokka = "2.2.0"
gradlePluginPublish = "2.1.1"
kotlin = "2.3.21"
kotlinxDatetime = "0.8.0-0.6.x-compat"
kover = "0.9.8"
kotlinter = "5.5.0"
mavenPublish = "0.36.0"

[libraries]
dokka-versioning-plugin = { module = "org.jetbrains.dokka:versioning-plugin", version.ref = "dokka" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

[plugins]
detekt = { id = "dev.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
