[versions]
detekt = "2.0.0-alpha.3"
kotlin = "2.3.21"
kotlinter = "5.5.0"

[plugins]
detekt = { id = "dev.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
java-gradle-plugin = { id = "java-gradle-plugin" }
