@file:OptIn(ExperimentalFiktionApi::class)

package dev.s7a.fiktion

import kotlin.reflect.KProperty1
import kotlin.reflect.KType
import kotlin.reflect.typeOf

/**
 * Per-call configuration for generating a [Root] value.
 */
public class FakeSpec<Root> {
    /**
     * Runtime type for [Root], supplied by fake entry points before user configuration runs.
     */
    internal lateinit var rootType: KType

    /**
     * Seed override for this generation call.
     */
    internal var seed: Long? = null

    /**
     * Mutable per-call rule configuration.
     */
    private val mutableConfig: MutableFiktionConfig = MutableFiktionConfig()

    /**
     * Explicit rules registered in this per-call scope.
     */
    internal val rules: List<DefaultGenerationSpec<*>>
        get() = mutableConfig.build().rules

    /**
     * Explicit config values registered in this per-call scope.
     */
    internal val configs: List<DefaultConfigSpec<*>>
        get() = mutableConfig.build().configs

    /**
     * Sets the seed for this generation call.
     */
    public infix fun withSeed(seed: Long) {
        this.seed = seed
    }

    /**
     * Configures the root value generated by this call.
     */
    public fun <Value : Any> using(
        key: FiktionConfig<in Root, Value>,
        value: Value,
    ) {
        using(key(value))
    }

    /**
     * Configures the root value generated by this call.
     */
    public infix fun <Value : Any> using(value: FiktionConfigSetting<in Root, Value>) {
        mutableConfig.add(DefaultConfigSpec(key = value.key, matcher = RuleMatcher.Type(rootType), value = value.value))
    }

    /**
     * Targets [property] on [Root].
     */
    @Suppress("DEPRECATION_ERROR")
    public inline fun <reified Value> property(property: KProperty1<Root, Value>): RuleTarget<Value> =
        property(property = property, value = typeOf<Value>())

    /**
     * Targets [property] on [Root].
     *
     * This low-level overload is intended for callers that already carry a [KType]. The caller must keep [value] and
     * the generator value type consistent.
     */
    @Deprecated("Use the reified property(property) overload.", level = DeprecationLevel.ERROR)
    public fun <Value> property(
        property: KProperty1<Root, Value>,
        value: KType,
    ): RuleTarget<Value> =
        target(
            segments = listOf(PathRuleSegment(ownerId = null, name = property.name, valueId = value.nonNullTypeId())),
            type = value,
        )

    /**
     * Targets a nested [path] starting from [Root].
     */
    public fun <Value> property(path: PropertyPath<Root, Value>): RuleTarget<Value> =
        target(segments = path.segments, type = path.valueType)

    /**
     * Groups declarations for [property] on [Root].
     */
    @Suppress("DEPRECATION_ERROR")
    public inline fun <reified Value> property(
        property: KProperty1<Root, Value>,
        noinline configure: RuleTarget<Value>.() -> Unit,
    ): RuleTarget<Value> = property(property).invoke(configure)

    /**
     * Groups declarations for a nested [path] starting from [Root].
     */
    public fun <Value> property(
        path: PropertyPath<Root, Value>,
        configure: RuleTarget<Value>.() -> Unit,
    ): RuleTarget<Value> = property(path).invoke(configure)

    /**
     * Targets properties generated while building [Root] whose value type is [value] and name is [name].
     *
     * This low-level overload is intended for callers that already carry a [KType]. The caller must keep [value] and
     * the generator value type consistent.
     */
    @Deprecated("Use the reified name<Value>(name) overload.", level = DeprecationLevel.ERROR)
    public fun name(
        name: String,
        value: KType,
    ): RuleTarget<*> = target<Any?>(RuleKey.Name(name, value), RuleMatcher.Name(name, value), targetType = value)

    /**
     * Targets properties generated while building [Root] whose name is [name], inferring the value type from the generator.
     */
    public fun name(name: String): RuleNameTarget =
        DefaultRuleNameTarget(
            key = { type -> RuleKey.Name(name, type) },
            matcher = { type -> RuleMatcher.Name(name, type) },
            register = mutableConfig::add,
        )

    /**
     * Targets properties generated while building [Root] whose value type is [value] and name matches [regex].
     *
     * This low-level overload is intended for callers that already carry a [KType]. The caller must keep [value] and
     * the generator value type consistent.
     */
    @Deprecated("Use the reified name<Value>(regex) overload.", level = DeprecationLevel.ERROR)
    public fun name(
        regex: Regex,
        value: KType,
    ): RuleTarget<*> =
        target<Any?>(RuleKey.RegexName(regex.pattern, regex.options, value), RuleMatcher.RegexName(regex, value), targetType = value)

    /**
     * Targets properties generated while building [Root] whose name matches [regex], inferring the value type from the generator.
     */
    public fun name(regex: Regex): RuleNameTarget =
        DefaultRuleNameTarget(
            key = { type -> RuleKey.RegexName(regex.pattern, regex.options, type) },
            matcher = { type -> RuleMatcher.RegexName(regex, type) },
            register = mutableConfig::add,
        )

    /**
     * Targets properties generated while building the current root whose value type is [Value] and name is [name].
     */
    @Suppress("DEPRECATION_ERROR", "UNCHECKED_CAST", "UNUSED_PARAMETER")
    public inline fun <reified Value> name(
        name: String,
        // Keeps this overload distinct from name(name: String), which returns RuleNameTarget.
        typed: Unit = Unit,
    ): RuleTarget<Value> = name(name, typeOf<Value>()) as RuleTarget<Value>

    /**
     * Targets properties generated while building the current root whose value type is [Value] and name matches [regex].
     */
    @Suppress("DEPRECATION_ERROR", "UNCHECKED_CAST", "UNUSED_PARAMETER")
    public inline fun <reified Value> name(
        regex: Regex,
        // Keeps this overload distinct from name(regex: Regex), which returns RuleNameTarget.
        typed: Unit = Unit,
    ): RuleTarget<Value> = name(regex, typeOf<Value>()) as RuleTarget<Value>

    /**
     * Generates [value] for this property.
     */
    @Suppress("DEPRECATION_ERROR")
    public inline infix fun <reified Value> KProperty1<Root, Value>.generates(value: Value): GenerationSpec<Value> =
        property(property = this, value = typeOf<Value>()).generates(value)

    /**
     * Generates this property by invoking [generator].
     */
    @Suppress("DEPRECATION_ERROR")
    public inline infix fun <reified Value> KProperty1<Root, Value>.generatesBy(
        noinline generator: Generator<Value>,
    ): GenerationSpec<Value> = property(property = this, value = typeOf<Value>()).generatesBy(generator)

    /**
     * Configures built-in or add-on generator behavior for this property.
     */
    @Suppress("DEPRECATION_ERROR")
    public inline fun <reified Value, ConfigValue : Any> KProperty1<Root, Value>.using(
        key: FiktionConfig<in Value, ConfigValue>,
        value: ConfigValue,
    ) {
        using(key(value))
    }

    /**
     * Configures built-in or add-on generator behavior for this property.
     */
    @Suppress("DEPRECATION_ERROR")
    public inline infix fun <reified Value, ConfigValue : Any> KProperty1<Root, Value>.using(
        value: FiktionConfigSetting<in Value, ConfigValue>,
    ) {
        property(property = this, value = typeOf<Value>()).using(value)
    }

    /**
     * Generates this property using Fiktion's automatic generation.
     */
    @Suppress("DEPRECATION_ERROR", "UNUSED_PARAMETER")
    public inline infix fun <reified Value> KProperty1<Root, Value>.generates(auto: Auto): GenerationSpec<Value> =
        property(property = this, value = typeOf<Value>()).generates(auto)

    /**
     * Generates this property using its constructor default value.
     */
    @Suppress("DEPRECATION_ERROR", "UNUSED_PARAMETER")
    public inline infix fun <reified Value> KProperty1<Root, Value>.generates(default: Default): GenerationSpec<Value> =
        property(property = this, value = typeOf<Value>()).generates(default)

    /**
     * Applies nested per-call configuration to this property.
     */
    @Suppress("DEPRECATION_ERROR")
    public inline operator fun <reified Value> KProperty1<Root, Value>.invoke(
        noinline configure: FakeSpec<Value>.() -> Unit,
    ): GenerationSpec<Value> = invoke(configure = configure, value = typeOf<Value>())

    /**
     * Applies nested per-call configuration to this property.
     *
     * This low-level overload is intended for callers that already carry a [KType]. The caller must keep [value] and
     * the generator value type consistent.
     */
    @Deprecated("Use the reified property invoke overload.", level = DeprecationLevel.ERROR)
    @Suppress("DEPRECATION_ERROR")
    public operator fun <Value> KProperty1<Root, Value>.invoke(
        configure: FakeSpec<Value>.() -> Unit,
        value: KType,
    ): GenerationSpec<Value> {
        configureNestedRules(
            prefix =
                listOf(
                    PathRuleSegment(
                        ownerId = null,
                        name = name,
                        valueId = value.nonNullTypeId(),
                    ),
                ),
            rootType = value,
            configure = configure,
        )
        return property(property = this, value = value) generates auto
    }

    /**
     * Generates [value] for this nested property path.
     */
    public infix fun <Value> PropertyPath<Root, Value>.generates(value: Value): GenerationSpec<Value> = property(this).generates(value)

    /**
     * Generates this nested property path by invoking [generator].
     */
    public infix fun <Value> PropertyPath<Root, Value>.generatesBy(generator: Generator<Value>): GenerationSpec<Value> =
        property(this).generatesBy(generator)

    /**
     * Generates this nested property path using Fiktion's automatic generation.
     */
    public infix fun <Value> PropertyPath<Root, Value>.generates(auto: Auto): GenerationSpec<Value> = property(this) generates auto

    /**
     * Generates this nested property path using its constructor default value.
     */
    public infix fun <Value> PropertyPath<Root, Value>.generates(default: Default): GenerationSpec<Value> =
        property(this) generates default

    /**
     * Applies nested per-call configuration to this property path.
     */
    public operator fun <Value> PropertyPath<Root, Value>.invoke(configure: FakeSpec<Value>.() -> Unit): GenerationSpec<Value> {
        configureNestedRules(prefix = segments, rootType = valueType, configure = configure)
        return property(this) generates auto
    }

    /**
     * Targets a property path represented as raw Kotlin properties.
     */
    private fun <Value> target(
        segments: List<PathRuleSegment>,
        type: KType,
    ): RuleTarget<Value> = target(RuleKey.Path(segments), RuleMatcher.Path(segments), targetType = type)

    /**
     * Registers rules from [configure] below a nested path [prefix].
     */
    private fun <Value> configureNestedRules(
        prefix: List<PathRuleSegment>,
        rootType: KType,
        configure: FakeSpec<Value>.() -> Unit,
    ) {
        val nestedSpec = FakeSpec<Value>()
        nestedSpec.rootType = rootType
        nestedSpec.configure()
        nestedSpec.rules.forEach { rule ->
            mutableConfig.add(rule.prefixedBy(prefix))
        }
        nestedSpec.configs.forEach { config ->
            mutableConfig.add(config.prefixedBy(prefix))
        }
    }

    /**
     * Registers a rule target using [key] for replacement and [matcher] for lookup.
     */
    private fun <Value> target(
        key: RuleKey,
        matcher: RuleMatcher,
        targetType: KType? = null,
    ): RuleTarget<Value> =
        DefaultRuleTarget(
            config = mutableConfig,
            key = key,
            matcher = matcher,
            targetType = targetType,
        )

    internal fun <Element> collectionElementTarget(collectionType: KType): RuleTarget<Element> =
        DefaultRuleTarget<Element>(
            config = mutableConfig,
            key = RuleKey.Container(parts = listOf(ContainerPart(kind = ContainerPart.Kind.Collection, container = collectionType))),
            matcher =
                RuleMatcher.Container(
                    parts = listOf(ContainerPart(kind = ContainerPart.Kind.Collection, container = collectionType)),
                ),
            targetType = collectionType.typeArgument(index = 0),
        )

    internal fun <Key> mapKeyTarget(mapType: KType): RuleTarget<Key> =
        DefaultRuleTarget<Key>(
            config = mutableConfig,
            key = RuleKey.Container(parts = listOf(ContainerPart(kind = ContainerPart.Kind.MapKey, container = mapType))),
            matcher = RuleMatcher.Container(parts = listOf(ContainerPart(kind = ContainerPart.Kind.MapKey, container = mapType))),
            targetType = mapType.typeArgument(index = 0),
        )

    internal fun <Value> mapValueTarget(mapType: KType): RuleTarget<Value> =
        DefaultRuleTarget<Value>(
            config = mutableConfig,
            key = RuleKey.Container(parts = listOf(ContainerPart(kind = ContainerPart.Kind.MapValue, container = mapType))),
            matcher = RuleMatcher.Container(parts = listOf(ContainerPart(kind = ContainerPart.Kind.MapValue, container = mapType))),
            targetType = mapType.typeArgument(index = 1),
        )
}
