@file:OptIn(ExperimentalFiktionApi::class)

@file:Suppress("ktlint:standard:max-line-length")

package dev.s7a.fiktion

import kotlin.reflect.KProperty1
import kotlin.reflect.KType
import kotlin.reflect.typeOf

/**
 * Per-call configuration for generating a [Root] value.
 */
public class FakeSpec<Root> {
    /**
     * Runtime type for [Root], supplied by fake entry points before user configuration runs.
     */
    internal lateinit var rootType: KType

    /**
     * Seed override for this generation call.
     */
    internal var seed: Long? = null

    /**
     * Mutable per-call rule configuration.
     */
    private val mutableConfig: MutableFiktionConfig = MutableFiktionConfig()

    /**
     * Explicit rules registered in this per-call scope.
     */
    internal val rules: List<DefaultGenerationSpec<*>>
        get() = mutableConfig.build().rules

    /**
     * Explicit config values registered in this per-call scope.
     */
    internal val configs: List<DefaultConfigSpec<*>>
        get() = mutableConfig.build().configs

    /**
     * Sets the seed for this generation call.
     */
    public infix fun withSeed(seed: Long) {
        this.seed = seed
    }

    /**
     * Configures the root value generated by this call.
     */
    public fun <Value : Any> using(
        key: FiktionConfig<in Root, Value>,
        value: Value,
    ) {
        using(key(value))
    }

    /**
     * Configures the root value generated by this call.
     */
    public infix fun <Value : Any> using(value: FiktionConfigSetting<in Root, Value>) {
        mutableConfig.add(DefaultConfigSpec(key = value.key, matcher = RuleMatcher.Type(rootType), value = value.value))
    }

    /**
     * Creates a dependent rule target using [property] for replacement and lookup.
     */
    @PublishedApi
    internal fun <Value> dependencyTarget(
        property: KProperty1<Root, Value>,
        value: KType,
        dependencies: List<KProperty1<Root, *>>,
        dependencyTypes: List<KType>,
    ): DependentRuleTarget<Value> =
        DependentRuleTarget(
            DefaultDependentRuleTarget(
                config = mutableConfig,
                key = RuleKey.Property(rootType, property.name, value),
                matcher = RuleMatcher.Property(rootType, property.name, value),
                dependencies =
                    dependencies.zip(dependencyTypes) { dependency, dependencyType ->
                        DependentProperty(owner = rootType, name = dependency.name, value = dependencyType)
                    },
            ),
        )

    /**
     * Targets [property] on [Root].
     */
    @Suppress("DEPRECATION_ERROR")
    public inline fun <reified Value> property(property: KProperty1<Root, Value>): RuleTarget<Value> =
        property(property = property, value = typeOf<Value>())

    /**
     * Targets [property] on [Root].
     *
     * This low-level overload is intended for callers that already carry a [KType]. The caller must keep [value] and
     * the generator value type consistent.
     */
    @Deprecated("Use the reified property(property) overload.", level = DeprecationLevel.ERROR)
    public fun <Value> property(
        property: KProperty1<Root, Value>,
        value: KType,
    ): RuleTarget<Value> =
        target(
            segments = listOf(PathRuleSegment(ownerId = null, name = property.name, valueId = value.nonNullTypeId())),
            type = value,
        )

    /**
     * Targets a nested [path] starting from [Root].
     */
    public fun <Value> property(path: PropertyPath<Root, Value>): RuleTarget<Value> =
        target(segments = path.segments, type = path.valueType)

    /**
     * Groups declarations for [property] on [Root].
     */
    @Suppress("DEPRECATION_ERROR")
    public inline fun <reified Value> property(
        property: KProperty1<Root, Value>,
        noinline configure: RuleTarget<Value>.() -> Unit,
    ): RuleTarget<Value> = property(property).invoke(configure)

    /**
     * Groups declarations for a nested [path] starting from [Root].
     */
    public fun <Value> property(
        path: PropertyPath<Root, Value>,
        configure: RuleTarget<Value>.() -> Unit,
    ): RuleTarget<Value> = property(path).invoke(configure)

    /**
     * Targets properties generated while building [Root] whose value type is [value] and name is [name].
     *
     * This low-level overload is intended for callers that already carry a [KType]. The caller must keep [value] and
     * the generator value type consistent.
     */
    @Deprecated("Use the reified name<Value>(name) overload.", level = DeprecationLevel.ERROR)
    public fun name(
        name: String,
        value: KType,
    ): RuleTarget<*> = target<Any?>(RuleKey.Name(name, value), RuleMatcher.Name(name, value), targetType = value)

    /**
     * Targets properties generated while building [Root] whose name is [name], inferring the value type from the generator.
     */
    public fun name(name: String): RuleNameTarget =
        DefaultRuleNameTarget(
            key = { type -> RuleKey.Name(name, type) },
            matcher = { type -> RuleMatcher.Name(name, type) },
            register = mutableConfig::add,
        )

    /**
     * Targets properties generated while building [Root] whose value type is [value] and name matches [regex].
     *
     * This low-level overload is intended for callers that already carry a [KType]. The caller must keep [value] and
     * the generator value type consistent.
     */
    @Deprecated("Use the reified name<Value>(regex) overload.", level = DeprecationLevel.ERROR)
    public fun name(
        regex: Regex,
        value: KType,
    ): RuleTarget<*> =
        target<Any?>(RuleKey.RegexName(regex.pattern, regex.options, value), RuleMatcher.RegexName(regex, value), targetType = value)

    /**
     * Targets properties generated while building [Root] whose name matches [regex], inferring the value type from the generator.
     */
    public fun name(regex: Regex): RuleNameTarget =
        DefaultRuleNameTarget(
            key = { type -> RuleKey.RegexName(regex.pattern, regex.options, type) },
            matcher = { type -> RuleMatcher.RegexName(regex, type) },
            register = mutableConfig::add,
        )

    /**
     * Targets properties generated while building the current root whose value type is [Value] and name is [name].
     */
    @Suppress("DEPRECATION_ERROR", "UNCHECKED_CAST", "UNUSED_PARAMETER")
    public inline fun <reified Value> name(
        name: String,
        // Keeps this overload distinct from name(name: String), which returns RuleNameTarget.
        typed: Unit = Unit,
    ): RuleTarget<Value> = name(name, typeOf<Value>()) as RuleTarget<Value>

    /**
     * Targets properties generated while building the current root whose value type is [Value] and name matches [regex].
     */
    @Suppress("DEPRECATION_ERROR", "UNCHECKED_CAST", "UNUSED_PARAMETER")
    public inline fun <reified Value> name(
        regex: Regex,
        // Keeps this overload distinct from name(regex: Regex), which returns RuleNameTarget.
        typed: Unit = Unit,
    ): RuleTarget<Value> = name(regex, typeOf<Value>()) as RuleTarget<Value>

    /**
     * Targets this root property with values generated from dependencies in declaration order.
     */
    public inline fun <reified Value> KProperty1<Root, Value>.dependsOn(
        vararg dependencies: KProperty1<Root, *>,
    ): DependentRuleTarget<Value> =
        dependencyTarget(
            property = this,
            value = typeOf<Value>(),
            dependencies = dependencies.toList(),
            dependencyTypes = List(size = dependencies.size) { typeOf<Any?>() },
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
    ): DependentRuleTarget1<Value, D1> =
        DependentRuleTarget1(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies = listOf(dependency1),
                dependencyTypes = listOf(typeOf<D1>()),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
    ): DependentRuleTarget2<Value, D1, D2> =
        DependentRuleTarget2(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies = listOf(dependency1, dependency2),
                dependencyTypes = listOf(typeOf<D1>(), typeOf<D2>()),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
    ): DependentRuleTarget3<Value, D1, D2, D3> =
        DependentRuleTarget3(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies = listOf(dependency1, dependency2, dependency3),
                dependencyTypes = listOf(typeOf<D1>(), typeOf<D2>(), typeOf<D3>()),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
    ): DependentRuleTarget4<Value, D1, D2, D3, D4> =
        DependentRuleTarget4(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies = listOf(dependency1, dependency2, dependency3, dependency4),
                dependencyTypes = listOf(typeOf<D1>(), typeOf<D2>(), typeOf<D3>(), typeOf<D4>()),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
    ): DependentRuleTarget5<Value, D1, D2, D3, D4, D5> =
        DependentRuleTarget5(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies = listOf(dependency1, dependency2, dependency3, dependency4, dependency5),
                dependencyTypes = listOf(typeOf<D1>(), typeOf<D2>(), typeOf<D3>(), typeOf<D4>(), typeOf<D5>()),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
    ): DependentRuleTarget6<Value, D1, D2, D3, D4, D5, D6> =
        DependentRuleTarget6(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies = listOf(dependency1, dependency2, dependency3, dependency4, dependency5, dependency6),
                dependencyTypes = listOf(typeOf<D1>(), typeOf<D2>(), typeOf<D3>(), typeOf<D4>(), typeOf<D5>(), typeOf<D6>()),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
    ): DependentRuleTarget7<Value, D1, D2, D3, D4, D5, D6, D7> =
        DependentRuleTarget7(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies = listOf(dependency1, dependency2, dependency3, dependency4, dependency5, dependency6, dependency7),
                dependencyTypes = listOf(typeOf<D1>(), typeOf<D2>(), typeOf<D3>(), typeOf<D4>(), typeOf<D5>(), typeOf<D6>(), typeOf<D7>()),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
    ): DependentRuleTarget8<Value, D1, D2, D3, D4, D5, D6, D7, D8> =
        DependentRuleTarget8(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
    ): DependentRuleTarget9<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9> =
        DependentRuleTarget9(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9, reified D10> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
        dependency10: KProperty1<Root, D10>,
    ): DependentRuleTarget10<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10> =
        DependentRuleTarget10(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                        dependency10,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                        typeOf<D10>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9, reified D10, reified D11> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
        dependency10: KProperty1<Root, D10>,
        dependency11: KProperty1<Root, D11>,
    ): DependentRuleTarget11<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11> =
        DependentRuleTarget11(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                        dependency10,
                        dependency11,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                        typeOf<D10>(),
                        typeOf<D11>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9, reified D10, reified D11, reified D12> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
        dependency10: KProperty1<Root, D10>,
        dependency11: KProperty1<Root, D11>,
        dependency12: KProperty1<Root, D12>,
    ): DependentRuleTarget12<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12> =
        DependentRuleTarget12(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                        dependency10,
                        dependency11,
                        dependency12,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                        typeOf<D10>(),
                        typeOf<D11>(),
                        typeOf<D12>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9, reified D10, reified D11, reified D12, reified D13> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
        dependency10: KProperty1<Root, D10>,
        dependency11: KProperty1<Root, D11>,
        dependency12: KProperty1<Root, D12>,
        dependency13: KProperty1<Root, D13>,
    ): DependentRuleTarget13<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13> =
        DependentRuleTarget13(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                        dependency10,
                        dependency11,
                        dependency12,
                        dependency13,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                        typeOf<D10>(),
                        typeOf<D11>(),
                        typeOf<D12>(),
                        typeOf<D13>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9, reified D10, reified D11, reified D12, reified D13, reified D14> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
        dependency10: KProperty1<Root, D10>,
        dependency11: KProperty1<Root, D11>,
        dependency12: KProperty1<Root, D12>,
        dependency13: KProperty1<Root, D13>,
        dependency14: KProperty1<Root, D14>,
    ): DependentRuleTarget14<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14> =
        DependentRuleTarget14(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                        dependency10,
                        dependency11,
                        dependency12,
                        dependency13,
                        dependency14,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                        typeOf<D10>(),
                        typeOf<D11>(),
                        typeOf<D12>(),
                        typeOf<D13>(),
                        typeOf<D14>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9, reified D10, reified D11, reified D12, reified D13, reified D14, reified D15> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
        dependency10: KProperty1<Root, D10>,
        dependency11: KProperty1<Root, D11>,
        dependency12: KProperty1<Root, D12>,
        dependency13: KProperty1<Root, D13>,
        dependency14: KProperty1<Root, D14>,
        dependency15: KProperty1<Root, D15>,
    ): DependentRuleTarget15<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15> =
        DependentRuleTarget15(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                        dependency10,
                        dependency11,
                        dependency12,
                        dependency13,
                        dependency14,
                        dependency15,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                        typeOf<D10>(),
                        typeOf<D11>(),
                        typeOf<D12>(),
                        typeOf<D13>(),
                        typeOf<D14>(),
                        typeOf<D15>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9, reified D10, reified D11, reified D12, reified D13, reified D14, reified D15, reified D16> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
        dependency10: KProperty1<Root, D10>,
        dependency11: KProperty1<Root, D11>,
        dependency12: KProperty1<Root, D12>,
        dependency13: KProperty1<Root, D13>,
        dependency14: KProperty1<Root, D14>,
        dependency15: KProperty1<Root, D15>,
        dependency16: KProperty1<Root, D16>,
    ): DependentRuleTarget16<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16> =
        DependentRuleTarget16(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                        dependency10,
                        dependency11,
                        dependency12,
                        dependency13,
                        dependency14,
                        dependency15,
                        dependency16,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                        typeOf<D10>(),
                        typeOf<D11>(),
                        typeOf<D12>(),
                        typeOf<D13>(),
                        typeOf<D14>(),
                        typeOf<D15>(),
                        typeOf<D16>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9, reified D10, reified D11, reified D12, reified D13, reified D14, reified D15, reified D16, reified D17> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
        dependency10: KProperty1<Root, D10>,
        dependency11: KProperty1<Root, D11>,
        dependency12: KProperty1<Root, D12>,
        dependency13: KProperty1<Root, D13>,
        dependency14: KProperty1<Root, D14>,
        dependency15: KProperty1<Root, D15>,
        dependency16: KProperty1<Root, D16>,
        dependency17: KProperty1<Root, D17>,
    ): DependentRuleTarget17<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16, D17> =
        DependentRuleTarget17(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                        dependency10,
                        dependency11,
                        dependency12,
                        dependency13,
                        dependency14,
                        dependency15,
                        dependency16,
                        dependency17,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                        typeOf<D10>(),
                        typeOf<D11>(),
                        typeOf<D12>(),
                        typeOf<D13>(),
                        typeOf<D14>(),
                        typeOf<D15>(),
                        typeOf<D16>(),
                        typeOf<D17>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9, reified D10, reified D11, reified D12, reified D13, reified D14, reified D15, reified D16, reified D17, reified D18> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
        dependency10: KProperty1<Root, D10>,
        dependency11: KProperty1<Root, D11>,
        dependency12: KProperty1<Root, D12>,
        dependency13: KProperty1<Root, D13>,
        dependency14: KProperty1<Root, D14>,
        dependency15: KProperty1<Root, D15>,
        dependency16: KProperty1<Root, D16>,
        dependency17: KProperty1<Root, D17>,
        dependency18: KProperty1<Root, D18>,
    ): DependentRuleTarget18<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16, D17, D18> =
        DependentRuleTarget18(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                        dependency10,
                        dependency11,
                        dependency12,
                        dependency13,
                        dependency14,
                        dependency15,
                        dependency16,
                        dependency17,
                        dependency18,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                        typeOf<D10>(),
                        typeOf<D11>(),
                        typeOf<D12>(),
                        typeOf<D13>(),
                        typeOf<D14>(),
                        typeOf<D15>(),
                        typeOf<D16>(),
                        typeOf<D17>(),
                        typeOf<D18>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9, reified D10, reified D11, reified D12, reified D13, reified D14, reified D15, reified D16, reified D17, reified D18, reified D19> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
        dependency10: KProperty1<Root, D10>,
        dependency11: KProperty1<Root, D11>,
        dependency12: KProperty1<Root, D12>,
        dependency13: KProperty1<Root, D13>,
        dependency14: KProperty1<Root, D14>,
        dependency15: KProperty1<Root, D15>,
        dependency16: KProperty1<Root, D16>,
        dependency17: KProperty1<Root, D17>,
        dependency18: KProperty1<Root, D18>,
        dependency19: KProperty1<Root, D19>,
    ): DependentRuleTarget19<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16, D17, D18, D19> =
        DependentRuleTarget19(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                        dependency10,
                        dependency11,
                        dependency12,
                        dependency13,
                        dependency14,
                        dependency15,
                        dependency16,
                        dependency17,
                        dependency18,
                        dependency19,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                        typeOf<D10>(),
                        typeOf<D11>(),
                        typeOf<D12>(),
                        typeOf<D13>(),
                        typeOf<D14>(),
                        typeOf<D15>(),
                        typeOf<D16>(),
                        typeOf<D17>(),
                        typeOf<D18>(),
                        typeOf<D19>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9, reified D10, reified D11, reified D12, reified D13, reified D14, reified D15, reified D16, reified D17, reified D18, reified D19, reified D20> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
        dependency10: KProperty1<Root, D10>,
        dependency11: KProperty1<Root, D11>,
        dependency12: KProperty1<Root, D12>,
        dependency13: KProperty1<Root, D13>,
        dependency14: KProperty1<Root, D14>,
        dependency15: KProperty1<Root, D15>,
        dependency16: KProperty1<Root, D16>,
        dependency17: KProperty1<Root, D17>,
        dependency18: KProperty1<Root, D18>,
        dependency19: KProperty1<Root, D19>,
        dependency20: KProperty1<Root, D20>,
    ): DependentRuleTarget20<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16, D17, D18, D19, D20> =
        DependentRuleTarget20(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                        dependency10,
                        dependency11,
                        dependency12,
                        dependency13,
                        dependency14,
                        dependency15,
                        dependency16,
                        dependency17,
                        dependency18,
                        dependency19,
                        dependency20,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                        typeOf<D10>(),
                        typeOf<D11>(),
                        typeOf<D12>(),
                        typeOf<D13>(),
                        typeOf<D14>(),
                        typeOf<D15>(),
                        typeOf<D16>(),
                        typeOf<D17>(),
                        typeOf<D18>(),
                        typeOf<D19>(),
                        typeOf<D20>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9, reified D10, reified D11, reified D12, reified D13, reified D14, reified D15, reified D16, reified D17, reified D18, reified D19, reified D20, reified D21> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
        dependency10: KProperty1<Root, D10>,
        dependency11: KProperty1<Root, D11>,
        dependency12: KProperty1<Root, D12>,
        dependency13: KProperty1<Root, D13>,
        dependency14: KProperty1<Root, D14>,
        dependency15: KProperty1<Root, D15>,
        dependency16: KProperty1<Root, D16>,
        dependency17: KProperty1<Root, D17>,
        dependency18: KProperty1<Root, D18>,
        dependency19: KProperty1<Root, D19>,
        dependency20: KProperty1<Root, D20>,
        dependency21: KProperty1<Root, D21>,
    ): DependentRuleTarget21<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16, D17, D18, D19, D20, D21> =
        DependentRuleTarget21(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                        dependency10,
                        dependency11,
                        dependency12,
                        dependency13,
                        dependency14,
                        dependency15,
                        dependency16,
                        dependency17,
                        dependency18,
                        dependency19,
                        dependency20,
                        dependency21,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                        typeOf<D10>(),
                        typeOf<D11>(),
                        typeOf<D12>(),
                        typeOf<D13>(),
                        typeOf<D14>(),
                        typeOf<D15>(),
                        typeOf<D16>(),
                        typeOf<D17>(),
                        typeOf<D18>(),
                        typeOf<D19>(),
                        typeOf<D20>(),
                        typeOf<D21>(),
                    ),
            ),
        )

    /**
     * Targets this root property with values generated from typed dependencies in declaration order.
     */
    public inline fun <reified Value, reified D1, reified D2, reified D3, reified D4, reified D5, reified D6, reified D7, reified D8, reified D9, reified D10, reified D11, reified D12, reified D13, reified D14, reified D15, reified D16, reified D17, reified D18, reified D19, reified D20, reified D21, reified D22> KProperty1<Root, Value>.dependsOn(
        dependency1: KProperty1<Root, D1>,
        dependency2: KProperty1<Root, D2>,
        dependency3: KProperty1<Root, D3>,
        dependency4: KProperty1<Root, D4>,
        dependency5: KProperty1<Root, D5>,
        dependency6: KProperty1<Root, D6>,
        dependency7: KProperty1<Root, D7>,
        dependency8: KProperty1<Root, D8>,
        dependency9: KProperty1<Root, D9>,
        dependency10: KProperty1<Root, D10>,
        dependency11: KProperty1<Root, D11>,
        dependency12: KProperty1<Root, D12>,
        dependency13: KProperty1<Root, D13>,
        dependency14: KProperty1<Root, D14>,
        dependency15: KProperty1<Root, D15>,
        dependency16: KProperty1<Root, D16>,
        dependency17: KProperty1<Root, D17>,
        dependency18: KProperty1<Root, D18>,
        dependency19: KProperty1<Root, D19>,
        dependency20: KProperty1<Root, D20>,
        dependency21: KProperty1<Root, D21>,
        dependency22: KProperty1<Root, D22>,
    ): DependentRuleTarget22<Value, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16, D17, D18, D19, D20, D21, D22> =
        DependentRuleTarget22(
            dependencyTarget(
                property = this,
                value = typeOf<Value>(),
                dependencies =
                    listOf(
                        dependency1,
                        dependency2,
                        dependency3,
                        dependency4,
                        dependency5,
                        dependency6,
                        dependency7,
                        dependency8,
                        dependency9,
                        dependency10,
                        dependency11,
                        dependency12,
                        dependency13,
                        dependency14,
                        dependency15,
                        dependency16,
                        dependency17,
                        dependency18,
                        dependency19,
                        dependency20,
                        dependency21,
                        dependency22,
                    ),
                dependencyTypes =
                    listOf(
                        typeOf<D1>(),
                        typeOf<D2>(),
                        typeOf<D3>(),
                        typeOf<D4>(),
                        typeOf<D5>(),
                        typeOf<D6>(),
                        typeOf<D7>(),
                        typeOf<D8>(),
                        typeOf<D9>(),
                        typeOf<D10>(),
                        typeOf<D11>(),
                        typeOf<D12>(),
                        typeOf<D13>(),
                        typeOf<D14>(),
                        typeOf<D15>(),
                        typeOf<D16>(),
                        typeOf<D17>(),
                        typeOf<D18>(),
                        typeOf<D19>(),
                        typeOf<D20>(),
                        typeOf<D21>(),
                        typeOf<D22>(),
                    ),
            ),
        )

    /**
     * Generates [value] for this property.
     */
    @Suppress("DEPRECATION_ERROR")
    public inline infix fun <reified Value> KProperty1<Root, Value>.generates(value: Value): GenerationSpec<Value> =
        property(property = this, value = typeOf<Value>()).generates(value)

    /**
     * Generates this property by invoking [generator].
     */
    @Suppress("DEPRECATION_ERROR")
    public inline infix fun <reified Value> KProperty1<Root, Value>.generatesBy(
        noinline generator: Generator<Value>,
    ): GenerationSpec<Value> = property(property = this, value = typeOf<Value>()).generatesBy(generator)

    /**
     * Configures built-in or add-on generator behavior for this property.
     */
    @Suppress("DEPRECATION_ERROR")
    public inline fun <reified Value, ConfigValue : Any> KProperty1<Root, Value>.using(
        key: FiktionConfig<in Value, ConfigValue>,
        value: ConfigValue,
    ) {
        using(key(value))
    }

    /**
     * Configures built-in or add-on generator behavior for this property.
     */
    @Suppress("DEPRECATION_ERROR")
    public inline infix fun <reified Value, ConfigValue : Any> KProperty1<Root, Value>.using(
        value: FiktionConfigSetting<in Value, ConfigValue>,
    ) {
        property(property = this, value = typeOf<Value>()).using(value)
    }

    /**
     * Generates this property using Fiktion's automatic generation.
     */
    @Suppress("DEPRECATION_ERROR", "UNUSED_PARAMETER")
    public inline infix fun <reified Value> KProperty1<Root, Value>.generates(auto: Auto): GenerationSpec<Value> =
        property(property = this, value = typeOf<Value>()).generates(auto)

    /**
     * Generates this property using its constructor default value.
     */
    @Suppress("DEPRECATION_ERROR", "UNUSED_PARAMETER")
    public inline infix fun <reified Value> KProperty1<Root, Value>.generates(default: Default): GenerationSpec<Value> =
        property(property = this, value = typeOf<Value>()).generates(default)

    /**
     * Applies nested per-call configuration to this property.
     */
    @Suppress("DEPRECATION_ERROR")
    public inline operator fun <reified Value> KProperty1<Root, Value>.invoke(
        noinline configure: FakeSpec<Value>.() -> Unit,
    ): GenerationSpec<Value> = invoke(configure = configure, value = typeOf<Value>())

    /**
     * Applies nested per-call configuration to this property.
     *
     * This low-level overload is intended for callers that already carry a [KType]. The caller must keep [value] and
     * the generator value type consistent.
     */
    @Deprecated("Use the reified property invoke overload.", level = DeprecationLevel.ERROR)
    @Suppress("DEPRECATION_ERROR")
    public operator fun <Value> KProperty1<Root, Value>.invoke(
        configure: FakeSpec<Value>.() -> Unit,
        value: KType,
    ): GenerationSpec<Value> {
        configureNestedRules(
            prefix =
                listOf(
                    PathRuleSegment(
                        ownerId = null,
                        name = name,
                        valueId = value.nonNullTypeId(),
                    ),
                ),
            rootType = value,
            configure = configure,
        )
        return property(property = this, value = value) generates auto
    }

    /**
     * Generates [value] for this nested property path.
     */
    public infix fun <Value> PropertyPath<Root, Value>.generates(value: Value): GenerationSpec<Value> = property(this).generates(value)

    /**
     * Generates this nested property path by invoking [generator].
     */
    public infix fun <Value> PropertyPath<Root, Value>.generatesBy(generator: Generator<Value>): GenerationSpec<Value> =
        property(this).generatesBy(generator)

    /**
     * Generates this nested property path using Fiktion's automatic generation.
     */
    public infix fun <Value> PropertyPath<Root, Value>.generates(auto: Auto): GenerationSpec<Value> = property(this) generates auto

    /**
     * Generates this nested property path using its constructor default value.
     */
    public infix fun <Value> PropertyPath<Root, Value>.generates(default: Default): GenerationSpec<Value> = property(this) generates default

    /**
     * Applies nested per-call configuration to this property path.
     */
    public operator fun <Value> PropertyPath<Root, Value>.invoke(configure: FakeSpec<Value>.() -> Unit): GenerationSpec<Value> {
        configureNestedRules(prefix = segments, rootType = valueType, configure = configure)
        return property(this) generates auto
    }

    /**
     * Targets a property path represented as raw Kotlin properties.
     */
    private fun <Value> target(
        segments: List<PathRuleSegment>,
        type: KType,
    ): RuleTarget<Value> = target(RuleKey.Path(segments), RuleMatcher.Path(segments), targetType = type)

    /**
     * Registers rules from [configure] below a nested path [prefix].
     */
    private fun <Value> configureNestedRules(
        prefix: List<PathRuleSegment>,
        rootType: KType,
        configure: FakeSpec<Value>.() -> Unit,
    ) {
        val nestedSpec = FakeSpec<Value>()
        nestedSpec.rootType = rootType
        nestedSpec.configure()
        nestedSpec.rules.forEach { rule ->
            mutableConfig.add(rule.prefixedBy(prefix))
        }
        nestedSpec.configs.forEach { config ->
            mutableConfig.add(config.prefixedBy(prefix))
        }
    }

    /**
     * Registers a rule target using [key] for replacement and [matcher] for lookup.
     */
    private fun <Value> target(
        key: RuleKey,
        matcher: RuleMatcher,
        targetType: KType? = null,
    ): RuleTarget<Value> =
        DefaultRuleTarget(
            config = mutableConfig,
            key = key,
            matcher = matcher,
            targetType = targetType,
        )

    internal fun <Element> collectionElementTarget(collectionType: KType): RuleTarget<Element> =
        DefaultRuleTarget(
            config = mutableConfig,
            key = RuleKey.Container(parts = listOf(ContainerPart(kind = ContainerPart.Kind.Collection, container = collectionType))),
            matcher =
                RuleMatcher.Container(
                    parts = listOf(ContainerPart(kind = ContainerPart.Kind.Collection, container = collectionType)),
                ),
            targetType = collectionType.typeArgument(index = 0),
        )

    internal fun <Key> mapKeyTarget(mapType: KType): RuleTarget<Key> =
        DefaultRuleTarget(
            config = mutableConfig,
            key = RuleKey.Container(parts = listOf(ContainerPart(kind = ContainerPart.Kind.MapKey, container = mapType))),
            matcher = RuleMatcher.Container(parts = listOf(ContainerPart(kind = ContainerPart.Kind.MapKey, container = mapType))),
            targetType = mapType.typeArgument(index = 0),
        )

    internal fun <Value> mapValueTarget(mapType: KType): RuleTarget<Value> =
        DefaultRuleTarget(
            config = mutableConfig,
            key = RuleKey.Container(parts = listOf(ContainerPart(kind = ContainerPart.Kind.MapValue, container = mapType))),
            matcher = RuleMatcher.Container(parts = listOf(ContainerPart(kind = ContainerPart.Kind.MapValue, container = mapType))),
            targetType = mapType.typeArgument(index = 1),
        )
}
